// Generated by CoffeeScript 1.6.3
var contributor;

contributor = require('../contributor');

exports.contributor = function(test) {
  test.expect(3);
  return contributor({
    gem: 'bcherny',
    github: 'eighttrackmind',
    npm: 'bcherny'
  }).then(function(counts) {
    var gemIsZero, githubIsMoreThan10, npmIsMoreThan10;
    gemIsZero = counts.gem === 0;
    githubIsMoreThan10 = counts.github > 10;
    npmIsMoreThan10 = counts.npm > 10;
    test.equals(gemIsZero, true);
    test.equals(githubIsMoreThan10, true);
    test.equals(npmIsMoreThan10, true);
    return test.done();
  });
};
