// Generated by CoffeeScript 1.6.3
var app, contributor, cors, error, express, validate, _;

_ = require('lodash');

contributor = require('./contributor');

cors = require('cors');

express = require('express');

app = express();

app.use(cors());

app.use(express.logger());

error = function(res, code, message) {
  return res.send(code, {
    status: code,
    message: message || ''
  });
};

validate = function(req, res) {
  if (!(_.keys(req.query)).length) {
    return error(res, 400, 'Error: API requires one or more identities passed as query parameters');
  }
};

app.get('/api', function(req, res) {
  var identities, param, platform, success, _i, _len, _ref;
  identities = {};
  success = function(counts) {
    return res.send(counts);
  };
  validate(req, res);
  _ref = contributor.support;
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    platform = _ref[_i];
    param = req.query[platform];
    if (param) {
      identities[platform] = param;
    }
  }
  return (contributor(identities)).then(success, function(e) {
    return error(res, 404, e);
  });
});

exports.app = app;
