// Generated by CoffeeScript 1.6.3
var apis, contributor, promise, whitelist, _;

_ = require('lodash');

promise = require('when');

apis = {
  github: require('github-repos'),
  npm: require('npm-packages')
};

module.exports = contributor;

whitelist = ['github', 'npm'];

contributor = function(identities) {
  var counts, deferred, done, have, need;
  if (identities == null) {
    identities = {};
  }
  deferred = promise.defer();
  counts = {};
  have = 0;
  need = 0;
  done = function(platform, count) {
    counts[platform] = count;
    if (++have === need) {
      return deferred.resolve(counts);
    } else {
      return deferred.notify(counts);
    }
  };
  whitelist.forEach(function(platform) {
    ++need;
    if (platform in identities) {
      return apis[platform](identities[platform]).then(function(count) {
        return done(platform, count);
      }, deferred.reject);
    }
  });
  return deferred.promise;
};

contributor({
  github: 'eighttrackmind',
  npm: 'bcherny'
}).then(function(counts) {
  return console.log(counts);
});
