// Generated by CoffeeScript 1.6.3
var app, contributor, ejs, express, fs, highlight, _;

_ = require('lodash');

contributor = require('./contributor');

express = require('express');

ejs = require('ejs');

fs = require('fs');

highlight = (require('highlight')).Highlight;

app = express();

app.use(express.logger());

app.get('/', function(req, res) {
  return fs.readFile('package.json', function(err, pkg) {
    pkg = JSON.parse(pkg);
    return fs.readFile('templates/index.ejs', function(err, template) {
      var html;
      if (err) {
        throw new Error(err);
      }
      html = ejs.render(template.toString(), {
        name: pkg.name,
        description: pkg.description,
        support: ['github', 'NPM', 'CPAN', 'Ruby Gems']
      });
      return res.send(html);
    });
  });
});

exports.app = app;
