// Generated by CoffeeScript 1.6.3
var app, config, contributor, ejs, express, fs, markdown, _;

_ = require('lodash');

contributor = require('./contributor');

express = require('express');

ejs = require('ejs');

fs = require('fs');

markdown = require('markdown');

config = {
  title: 'contributor.io',
  description: 'Fetch your contribution counts for various platforms (Github, NPM, Gem, CPAN, ...)'
};

app = express();

app.use(express.logger());

app.get('/', function(req, res) {
  return fs.readFile('package.json', function(err, pkg) {
    pkg = JSON.parse(pkg);
    return fs.readFile('README.md', function(err, readme) {
      var marked;
      marked = markdown.parse(readme);
      return fs.readFile('templates/index.ejs', function(err, template) {
        if (err) {
          throw new Error(err);
        }
        return res.send(ejs.render(template.toString(), {
          name: pkg.name,
          description: pkg.description
        }));
      });
    });
  });
});

exports.app = app;
