// Generated by CoffeeScript 1.6.3
var app, config, contributor, express;

contributor = require('./contributor');

express = require('express');

config = {
  port: 8000
};

app = express();

app.use(cors());

app.use(express.bodyParser());

app.use(express.logger());

app.listen(config.port);

console.log(contributor);

app.get('/', function(req, res) {
  var npm;
  return npm = req.query.npm;
});
